package it.frank.conformita.core.dto;

import it.frank.conformita.core.entity.DestinazioneUso;
import it.frank.conformita.core.entity.SistemaDistribuzione;
import it.frank.conformita.core.entity.TensioneImpianto;
import it.frank.conformita.core.entity.TipoIntervento;
import java.time.LocalDate;
import java.util.List;

/** Rebuild {@link PraticaDto} when a wizard step updates a subset of fields. */
public final class PraticaDtoCopy {

    private PraticaDtoCopy() {}

    public static PraticaDto withCommittente(
            PraticaDto b,
            String comuneImpianto,
            String provincia,
            String committenteNome,
            String committenteCodiceFiscale,
            String indirizzoImpianto,
            String indirizzoCommittente,
            String proprietarioDescrizione,
            String comune,
            String cap) {
        return copy(
                b,
                comuneImpianto,
                provincia,
                b.protocollo(),
                b.dataProtocollo(),
                b.descrizioneImpianto(),
                committenteNome,
                committenteCodiceFiscale,
                indirizzoImpianto,
                indirizzoCommittente,
                proprietarioDescrizione,
                comune,
                cap,
                b.tipoIntervento(),
                b.destinazioneUso(),
                b.altriUsi(),
                b.dataInizio(),
                b.potenzaKw(),
                b.potenzaImpegnabileKw(),
                b.potenzaInstallataKw(),
                b.fotovoltaico(),
                b.altroIntervento(),
                b.tensione(),
                b.tensioneNominale(),
                b.sistemaDistribuzione(),
                b.normaTecnica(),
                b.dichiaraProgetto(),
                b.dichiaraNorma(),
                b.dichiaraMateriali(),
                b.dichiaraControlli(),
                b.allegatoProgetto(),
                b.allegatoMateriali(),
                b.allegatoSchema(),
                b.riferimentiPrecedenti(),
                b.dataDichiarazione(),
                b.responsabileTecnicoNome(),
                b.descrizioneOpere(),
                b.provaVistaSezioni(),
                b.provaVistaBagno(),
                b.provaVistaInterruttori(),
                b.telefonoAssistenza(),
                b.schemaAllegatoPath(),
                b.schemaUnifilareJsonPath(),
                b.unifilareSchemaId(),
                b.materiali(),
                b.verifiche());
    }

    public static PraticaDto withIntervento(
            PraticaDto b,
            String descrizioneImpianto,
            TipoIntervento tipoIntervento,
            DestinazioneUso destinazioneUso,
            String altriUsi,
            LocalDate dataInizio,
            Double potenzaKw,
            Double potenzaImpegnabileKw,
            Double potenzaInstallataKw,
            boolean fotovoltaico,
            boolean altroIntervento,
            TensioneImpianto tensione,
            String normaTecnica) {
        return copy(
                b,
                b.comuneImpianto(),
                b.provincia(),
                b.protocollo(),
                b.dataProtocollo(),
                descrizioneImpianto,
                b.committenteNome(),
                b.committenteCodiceFiscale(),
                b.indirizzoImpianto(),
                b.indirizzoCommittente(),
                b.proprietarioDescrizione(),
                b.comune(),
                b.cap(),
                tipoIntervento,
                destinazioneUso,
                altriUsi,
                dataInizio,
                potenzaKw,
                potenzaImpegnabileKw,
                potenzaInstallataKw,
                fotovoltaico,
                altroIntervento,
                tensione,
                b.tensioneNominale(),
                b.sistemaDistribuzione(),
                normaTecnica,
                b.dichiaraProgetto(),
                b.dichiaraNorma(),
                b.dichiaraMateriali(),
                b.dichiaraControlli(),
                b.allegatoProgetto(),
                b.allegatoMateriali(),
                b.allegatoSchema(),
                b.riferimentiPrecedenti(),
                b.dataDichiarazione(),
                b.responsabileTecnicoNome(),
                b.descrizioneOpere(),
                b.provaVistaSezioni(),
                b.provaVistaBagno(),
                b.provaVistaInterruttori(),
                b.telefonoAssistenza(),
                b.schemaAllegatoPath(),
                b.schemaUnifilareJsonPath(),
                b.unifilareSchemaId(),
                b.materiali(),
                b.verifiche());
    }

    public static PraticaDto withDichiarazione(
            PraticaDto b,
            boolean dichiaraProgetto,
            boolean dichiaraNorma,
            boolean dichiaraMateriali,
            boolean dichiaraControlli,
            boolean allegatoProgetto,
            boolean allegatoMateriali,
            boolean allegatoSchema,
            String riferimentiPrecedenti,
            LocalDate dataDichiarazione,
            String responsabileTecnicoNome) {
        return copy(
                b,
                b.comuneImpianto(),
                b.provincia(),
                b.protocollo(),
                b.dataProtocollo(),
                b.descrizioneImpianto(),
                b.committenteNome(),
                b.committenteCodiceFiscale(),
                b.indirizzoImpianto(),
                b.indirizzoCommittente(),
                b.proprietarioDescrizione(),
                b.comune(),
                b.cap(),
                b.tipoIntervento(),
                b.destinazioneUso(),
                b.altriUsi(),
                b.dataInizio(),
                b.potenzaKw(),
                b.potenzaImpegnabileKw(),
                b.potenzaInstallataKw(),
                b.fotovoltaico(),
                b.altroIntervento(),
                b.tensione(),
                b.tensioneNominale(),
                b.sistemaDistribuzione(),
                b.normaTecnica(),
                dichiaraProgetto,
                dichiaraNorma,
                dichiaraMateriali,
                dichiaraControlli,
                allegatoProgetto,
                allegatoMateriali,
                allegatoSchema,
                riferimentiPrecedenti,
                dataDichiarazione,
                responsabileTecnicoNome,
                b.descrizioneOpere(),
                b.provaVistaSezioni(),
                b.provaVistaBagno(),
                b.provaVistaInterruttori(),
                b.telefonoAssistenza(),
                b.schemaAllegatoPath(),
                b.schemaUnifilareJsonPath(),
                b.unifilareSchemaId(),
                b.materiali(),
                b.verifiche());
    }

    public static PraticaDto withRelazioneTecnica(
            PraticaDto b,
            String tensioneNominale,
            SistemaDistribuzione sistemaDistribuzione,
            Double potenzaInstallataKw,
            String descrizioneOpere) {
        return copy(
                b,
                b.comuneImpianto(),
                b.provincia(),
                b.protocollo(),
                b.dataProtocollo(),
                b.descrizioneImpianto(),
                b.committenteNome(),
                b.committenteCodiceFiscale(),
                b.indirizzoImpianto(),
                b.indirizzoCommittente(),
                b.proprietarioDescrizione(),
                b.comune(),
                b.cap(),
                b.tipoIntervento(),
                b.destinazioneUso(),
                b.altriUsi(),
                b.dataInizio(),
                b.potenzaKw(),
                b.potenzaImpegnabileKw(),
                potenzaInstallataKw,
                b.fotovoltaico(),
                b.altroIntervento(),
                b.tensione(),
                tensioneNominale,
                sistemaDistribuzione,
                b.normaTecnica(),
                b.dichiaraProgetto(),
                b.dichiaraNorma(),
                b.dichiaraMateriali(),
                b.dichiaraControlli(),
                b.allegatoProgetto(),
                b.allegatoMateriali(),
                b.allegatoSchema(),
                b.riferimentiPrecedenti(),
                b.dataDichiarazione(),
                b.responsabileTecnicoNome(),
                descrizioneOpere,
                b.provaVistaSezioni(),
                b.provaVistaBagno(),
                b.provaVistaInterruttori(),
                b.telefonoAssistenza(),
                b.schemaAllegatoPath(),
                b.schemaUnifilareJsonPath(),
                b.unifilareSchemaId(),
                b.materiali(),
                b.verifiche());
    }

    public static PraticaDto withMateriali(PraticaDto b, List<MaterialeRigaDto> materiali) {
        return copy(
                b,
                b.comuneImpianto(),
                b.provincia(),
                b.protocollo(),
                b.dataProtocollo(),
                b.descrizioneImpianto(),
                b.committenteNome(),
                b.committenteCodiceFiscale(),
                b.indirizzoImpianto(),
                b.indirizzoCommittente(),
                b.proprietarioDescrizione(),
                b.comune(),
                b.cap(),
                b.tipoIntervento(),
                b.destinazioneUso(),
                b.altriUsi(),
                b.dataInizio(),
                b.potenzaKw(),
                b.potenzaImpegnabileKw(),
                b.potenzaInstallataKw(),
                b.fotovoltaico(),
                b.altroIntervento(),
                b.tensione(),
                b.tensioneNominale(),
                b.sistemaDistribuzione(),
                b.normaTecnica(),
                b.dichiaraProgetto(),
                b.dichiaraNorma(),
                b.dichiaraMateriali(),
                b.dichiaraControlli(),
                b.allegatoProgetto(),
                b.allegatoMateriali(),
                b.allegatoSchema(),
                b.riferimentiPrecedenti(),
                b.dataDichiarazione(),
                b.responsabileTecnicoNome(),
                b.descrizioneOpere(),
                b.provaVistaSezioni(),
                b.provaVistaBagno(),
                b.provaVistaInterruttori(),
                b.telefonoAssistenza(),
                b.schemaAllegatoPath(),
                b.schemaUnifilareJsonPath(),
                b.unifilareSchemaId(),
                materiali,
                b.verifiche());
    }

    public static PraticaDto withVerifiche(
            PraticaDto b,
            boolean provaVistaSezioni,
            boolean provaVistaBagno,
            boolean provaVistaInterruttori,
            List<VerificaRigaDto> verifiche) {
        return copy(
                b,
                b.comuneImpianto(),
                b.provincia(),
                b.protocollo(),
                b.dataProtocollo(),
                b.descrizioneImpianto(),
                b.committenteNome(),
                b.committenteCodiceFiscale(),
                b.indirizzoImpianto(),
                b.indirizzoCommittente(),
                b.proprietarioDescrizione(),
                b.comune(),
                b.cap(),
                b.tipoIntervento(),
                b.destinazioneUso(),
                b.altriUsi(),
                b.dataInizio(),
                b.potenzaKw(),
                b.potenzaImpegnabileKw(),
                b.potenzaInstallataKw(),
                b.fotovoltaico(),
                b.altroIntervento(),
                b.tensione(),
                b.tensioneNominale(),
                b.sistemaDistribuzione(),
                b.normaTecnica(),
                b.dichiaraProgetto(),
                b.dichiaraNorma(),
                b.dichiaraMateriali(),
                b.dichiaraControlli(),
                b.allegatoProgetto(),
                b.allegatoMateriali(),
                b.allegatoSchema(),
                b.riferimentiPrecedenti(),
                b.dataDichiarazione(),
                b.responsabileTecnicoNome(),
                b.descrizioneOpere(),
                provaVistaSezioni,
                provaVistaBagno,
                provaVistaInterruttori,
                b.telefonoAssistenza(),
                b.schemaAllegatoPath(),
                b.schemaUnifilareJsonPath(),
                b.unifilareSchemaId(),
                b.materiali(),
                verifiche);
    }

    public static PraticaDto withLibretto(
            PraticaDto b, String telefonoAssistenza, String schemaAllegatoPath, String schemaUnifilareJsonPath) {
        return copy(
                b,
                b.comuneImpianto(),
                b.provincia(),
                b.protocollo(),
                b.dataProtocollo(),
                b.descrizioneImpianto(),
                b.committenteNome(),
                b.committenteCodiceFiscale(),
                b.indirizzoImpianto(),
                b.indirizzoCommittente(),
                b.proprietarioDescrizione(),
                b.comune(),
                b.cap(),
                b.tipoIntervento(),
                b.destinazioneUso(),
                b.altriUsi(),
                b.dataInizio(),
                b.potenzaKw(),
                b.potenzaImpegnabileKw(),
                b.potenzaInstallataKw(),
                b.fotovoltaico(),
                b.altroIntervento(),
                b.tensione(),
                b.tensioneNominale(),
                b.sistemaDistribuzione(),
                b.normaTecnica(),
                b.dichiaraProgetto(),
                b.dichiaraNorma(),
                b.dichiaraMateriali(),
                b.dichiaraControlli(),
                b.allegatoProgetto(),
                b.allegatoMateriali(),
                b.allegatoSchema(),
                b.riferimentiPrecedenti(),
                b.dataDichiarazione(),
                b.responsabileTecnicoNome(),
                b.descrizioneOpere(),
                b.provaVistaSezioni(),
                b.provaVistaBagno(),
                b.provaVistaInterruttori(),
                telefonoAssistenza,
                schemaAllegatoPath,
                schemaUnifilareJsonPath,
                b.unifilareSchemaId(),
                b.materiali(),
                b.verifiche());
    }

    public static PraticaDto withSchemaPaths(PraticaDto b, String schemaAllegatoPath, String schemaUnifilareJsonPath) {
        return withLibretto(b, b.telefonoAssistenza(), schemaAllegatoPath, schemaUnifilareJsonPath);
    }

    public static PraticaDto withAllegatoSchema(PraticaDto b, boolean allegatoSchema) {
        return withDichiarazione(
                b,
                b.dichiaraProgetto(),
                b.dichiaraNorma(),
                b.dichiaraMateriali(),
                b.dichiaraControlli(),
                b.allegatoProgetto(),
                b.allegatoMateriali(),
                allegatoSchema,
                b.riferimentiPrecedenti(),
                b.dataDichiarazione(),
                b.responsabileTecnicoNome());
    }

    public static PraticaDto withUnifilareSchemaId(PraticaDto b, Long unifilareSchemaId) {
        return copy(
                b,
                b.comuneImpianto(),
                b.provincia(),
                b.protocollo(),
                b.dataProtocollo(),
                b.descrizioneImpianto(),
                b.committenteNome(),
                b.committenteCodiceFiscale(),
                b.indirizzoImpianto(),
                b.indirizzoCommittente(),
                b.proprietarioDescrizione(),
                b.comune(),
                b.cap(),
                b.tipoIntervento(),
                b.destinazioneUso(),
                b.altriUsi(),
                b.dataInizio(),
                b.potenzaKw(),
                b.potenzaImpegnabileKw(),
                b.potenzaInstallataKw(),
                b.fotovoltaico(),
                b.altroIntervento(),
                b.tensione(),
                b.tensioneNominale(),
                b.sistemaDistribuzione(),
                b.normaTecnica(),
                b.dichiaraProgetto(),
                b.dichiaraNorma(),
                b.dichiaraMateriali(),
                b.dichiaraControlli(),
                b.allegatoProgetto(),
                b.allegatoMateriali(),
                b.allegatoSchema(),
                b.riferimentiPrecedenti(),
                b.dataDichiarazione(),
                b.responsabileTecnicoNome(),
                b.descrizioneOpere(),
                b.provaVistaSezioni(),
                b.provaVistaBagno(),
                b.provaVistaInterruttori(),
                b.telefonoAssistenza(),
                b.schemaAllegatoPath(),
                b.schemaUnifilareJsonPath(),
                unifilareSchemaId,
                b.materiali(),
                b.verifiche());
    }

    @SuppressWarnings("java:S107")
    private static PraticaDto copy(
            PraticaDto b,
            String comuneImpianto,
            String provincia,
            String protocollo,
            LocalDate dataProtocollo,
            String descrizioneImpianto,
            String committenteNome,
            String committenteCodiceFiscale,
            String indirizzoImpianto,
            String indirizzoCommittente,
            String proprietarioDescrizione,
            String comune,
            String cap,
            TipoIntervento tipoIntervento,
            DestinazioneUso destinazioneUso,
            String altriUsi,
            LocalDate dataInizio,
            Double potenzaKw,
            Double potenzaImpegnabileKw,
            Double potenzaInstallataKw,
            boolean fotovoltaico,
            boolean altroIntervento,
            TensioneImpianto tensione,
            String tensioneNominale,
            SistemaDistribuzione sistemaDistribuzione,
            String normaTecnica,
            boolean dichiaraProgetto,
            boolean dichiaraNorma,
            boolean dichiaraMateriali,
            boolean dichiaraControlli,
            boolean allegatoProgetto,
            boolean allegatoMateriali,
            boolean allegatoSchema,
            String riferimentiPrecedenti,
            LocalDate dataDichiarazione,
            String responsabileTecnicoNome,
            String descrizioneOpere,
            boolean provaVistaSezioni,
            boolean provaVistaBagno,
            boolean provaVistaInterruttori,
            String telefonoAssistenza,
            String schemaAllegatoPath,
            String schemaUnifilareJsonPath,
            Long unifilareSchemaId,
            List<MaterialeRigaDto> materiali,
            List<VerificaRigaDto> verifiche) {
        return new PraticaDto(
                b.id(),
                b.createdAt(),
                b.updatedAt(),
                b.stato(),
                comuneImpianto,
                provincia,
                protocollo,
                dataProtocollo,
                descrizioneImpianto,
                committenteNome,
                committenteCodiceFiscale,
                indirizzoImpianto,
                indirizzoCommittente,
                proprietarioDescrizione,
                comune,
                cap,
                tipoIntervento,
                destinazioneUso,
                altriUsi,
                dataInizio,
                potenzaKw,
                potenzaImpegnabileKw,
                potenzaInstallataKw,
                fotovoltaico,
                altroIntervento,
                tensione,
                tensioneNominale,
                sistemaDistribuzione,
                normaTecnica,
                dichiaraProgetto,
                dichiaraNorma,
                dichiaraMateriali,
                dichiaraControlli,
                allegatoProgetto,
                allegatoMateriali,
                allegatoSchema,
                riferimentiPrecedenti,
                dataDichiarazione,
                responsabileTecnicoNome,
                descrizioneOpere,
                provaVistaSezioni,
                provaVistaBagno,
                provaVistaInterruttori,
                telefonoAssistenza,
                schemaAllegatoPath,
                schemaUnifilareJsonPath,
                unifilareSchemaId,
                materiali,
                verifiche);
    }
}
